[build]
  # Directorio donde se encuentra el código fuente
  base = "."
  
  # Comando para instalar dependencias
  command = "npm install && npm run build"
  
  # Directorio donde se generan los archivos estáticos
  publish = "dist"

[build.environment]
  # Versión de Node.js
  NODE_VERSION = "18"

# Configuración de redirecciones para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de headers para optimización
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Configuración específica para archivos estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
